### PR TITLE
Add fabricstore

### LINKED ISSUE #26: Add fabricstore

### PR DESCRIPTION
**Pull request by piedup**
Starts a hyperledger fabric network with a fabricstore. Resolves #26

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/27)

### CODE REVIEW

**Comment by alexppxela** [comment]
*[agent-basic-js/generator.json, line 14 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKV-cxKTRit8qQg4fT:-KyKV-cxKTRit8qQg4fU:bb48udm) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/generator.json#L14)):*
> ```JSON
>     "filetmpop": "stratumn/filetmpop:0.1.0",
>     "tmstore": "stratumn/tmstore:0.1.0",
>     "fabricstore": "stratumn/fabricstore",
> ```

It should be better to release a fabricstore version and mentioned it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/27)*

**Comment by alexppxela** [comment]
Reviewed 1 of 61 files at r1.
Review status: 1 of 61 files reviewed at latest revision, 14 unresolved discussions.

---

*[agent-basic-js/generator.json, line 84 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKVmywqhWiFGRvdZJy:-KyKVmywqhWiFGRvdZJz:b-oj9pjd) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/generator.json#L84)):*
> ```JSON
>         {
>           "input": "2",
>           "value": "fabricstore",
> ```

Using "2" will impact all sdk unit tests. It should be better to add fabricstore after dummystore or update sdk generator tests.

---

*[agent-basic-js/files/.gitignore, line 4 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKY5W3IOGNUFANeNeZ:-KyKY5W49zpLw-70yhqS:b-5uhtd6) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/.gitignore#L4)):*
> ```
> node_modules
> {{"*.secret.env"}}
> fabric/data
> ```

Why this? You do not have fabric/data files.

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 7 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKYb-aJH-oCFKQdUQV:-KyKYWPXa4MpE0e_t-ZU:bs0d0jf) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L7)):*
>     echo "========= ERROR !!! FAILED to initialize netw
I prefer having errors on stderr using 1>&2

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 8 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKZ45BdgAW6MvG9Y6r:-KyKZ45BdgAW6MvG9Y6s:bdt3cxe) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L8)):*
> ```Shell
> 	if [ $1 -ne 0 ] ; then
> 		echo "!!!!!!!!!!!!!!! "$2" !!!!!!!!!!!!!!!!"
>     echo "========= ERROR !!! FAILED to initialize network ==========="
> ```

nit: It seems it is missing an indentation for this line

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 17 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKZQPYj5LG5uUnSYkz:-KyKZQPZhFKdfc-X9GEN:b-cktvx3) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L17)):*
> ```Shell
> 	peer channel create -o orderer.example.com:7050 -c $CHANNEL_NAME -f $CONFIG_PATH/channel.tx --tls $CORE_PEER_TLS_ENABLED --cafile $ORDERER_CA >&log.txt
> 	res=$?
> 	# cat log.txt
> ```

nit: commented code

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 19 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKZXjTaVpamZo3HBn1:-KyKZXjTaVpamZo3HBn2:b-l6mkri) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L19)):*
> ```Shell
> 	# cat log.txt
> 	if [ $res -ne 0 -a $COUNTER -lt $MAX_RETRY ]; then
> 		COUNTER=` expr $COUNTER + 1`
> ```

nit: unnecessary space

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 22 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKc70O7PMdyfz3pntb:-KyKc70O7PMdyfz3pntc:bnoqj1y) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L22)):*
> ```Shell
> 		echo "Failed to create channel, retrying in $DELAY seconds"
> 		sleep $DELAY
> 		createChannelWithRetry
> ```

I don't know if recursion is a good way in shell.
Prefer loop like 

counter=0
while [ $counter -lt $MAX_RETRY ]; do
	peer channel create -o orderer.example.com:7050 -c $CHANNEL_NAME -f $CONFIG_PATH/channel.tx --tls $CORE_PEER_TLS_ENABLED --cafile $ORDERER_CA >&log.txt
	res=$?
	if [ $? -eq 0  ]; then
		break
	fi
	echo "Failed to create channel, retrying in $DELAY seconds"
	sleep $DELAY
done
verifyResult `test $counter -lt $MAX_RETRY` "After $MAX_RETRY attempts, failed to create channel"
}

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 32 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKZWBpCz4u3p6ea5vp:-KyKZWBpCz4u3p6ea5vq:b-cktvx3) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L32)):*
> ```Shell
> 	peer channel join -b mychannel.block >&log.txt
> 	res=$?
> 	# cat log.txt
> ```

nit: commented code

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 37 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKdrAGguPq-bh_1-Vf:-KyKdrAGguPq-bh_1-Vg:b7fr1fq) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L37)):*
> ```Shell
> 		echo "Failed to join peer to channel, retrying in $DELAY seconds"
> 		sleep $DELAY
> 		joinWithRetry
> ```

same as below comment about recursion

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 46 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKdzFs81XVFCmwGsrg:-KyKdzFs81XVFCmwGsrh:b-x6k54l) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L46)):*
> ```Shell
> instantiateIfNeeded () {
> 	peer chaincode query -C mychannel -n pop -c '{"Function":"GetValue","Args":["none"]}' >/dev/null
> 	res=$?
> ```

unnecessary variable

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 50 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKe2HPe7cV__uLItP_:-KyKe2HPe7cV__uLItPa:b-rnqs2r) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L50)):*
> ```Shell
> 		peer chaincode instantiate -o orderer.example.com:7050 --tls $CORE_PEER_TLS_ENABLED --cafile $ORDERER_CA -C $CHANNEL_NAME -n pop -v 1.0 -c '{"Args":[]}' -P "AND ('Org1MSP.member')"
> 		res=$?
> 		verifyResult $res "Chaincode instantiation on peer on channel '$CHANNEL_NAME' failed"
> ```

use $? directly

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 66 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKb1L3YtFqUhRlSYVG:-KyKb1L3YtFqUhRlSYVH:b-cb9g4) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L66)):*
> ```Shell
> peer channel update -o orderer.example.com:7050 -c $CHANNEL_NAME -f $CONFIG_PATH/Org1MSPanchors.tx --tls $CORE_PEER_TLS_ENABLED --cafile $ORDERER_CA
> res=$?
> verifyResult $res  "Anchor peer update failed"
> ```

You can use $? directly

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 72 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKb4lkLQLOwCX7ftFf:-KyKb4lkLQLOwCX7ftFg:b-y9meh4) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L72)):*
> ```Shell
> peer chaincode install -n pop -v 1.0 -p github.com/stratumn/chaincode/pop
> res=$?
> verifyResult $res "Chaincode installation on remote peer has Failed"
> ```

Same as below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/27)*

**Comment by alexppxela** [comment]
General comment:
Does your example works using example.com without changes?
Should it be better to use localhost?

 I trust you for all added file.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/27#-:-KyKeDF2HbcY8b8YT_Gu:b-7p2ity)*

**Comment by alexppxela** [comment]
Reviewed 60 of 61 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/27)*

**Comment by alexppxela** [comment]
*[agent-basic-js/files/fabric/scripts/install.sh, line 1 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKk0qA_7aVyxbO4LeU:-KyKk0qA_7aVyxbO4LeV:b-ohmqr) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L1)):*
> ```Shell
> MAX_RETRY=5
> ```

I forgot. The first line of your shell script must be
`#!/bin/sh`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/27)*

**Comment by piedup** [comment]
Review status: 59 of 61 files reviewed at latest revision, 15 unresolved discussions.

---

*[agent-basic-js/generator.json, line 84 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKVmywqhWiFGRvdZJy:-KyKofoj4KiMdm1t99Kt:b-g2dzm9) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/generator.json#L84)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Using "2" will impact all sdk unit tests. It should be better to add fabricstore after dummystore or update sdk generator tests.
</blockquote></details>

I've changed the order to what it was. However I think it might be good to change the order in another commit because I don't think it makes sense to put fabric after dummy store.

---

*[agent-basic-js/files/.gitignore, line 4 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKY5W3IOGNUFANeNeZ:-KyKs6nN9VsTObxydQTD:bw08qwj) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/.gitignore#L4)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why this? You do not have fabric/data files.
</blockquote></details>

When starting the fabric network a data folder is created under fabric to store the couchdb data (world state). I don't think it should be pushed to a git repo.

---

*[agent-basic-js/files/fabric/scripts/install.sh, line 22 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKc70O7PMdyfz3pntb:-KyKtfh2K3dC3KT--bS0:bop77gn) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/files/fabric/scripts/install.sh#L22)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I don't know if recursion is a good way in shell.
Prefer loop like 

counter=0
while [ $counter -lt $MAX_RETRY ]; do
	peer channel create -o orderer.example.com:7050 -c $CHANNEL_NAME -f $CONFIG_PATH/channel.tx --tls $CORE_PEER_TLS_ENABLED --cafile $ORDERER_CA >&log.txt
	res=$?
	if [ $? -eq 0  ]; then
		break
	fi
	echo "Failed to create channel, retrying in $DELAY seconds"
	sleep $DELAY
done
verifyResult `test $counter -lt $MAX_RETRY` "After $MAX_RETRY attempts, failed to create channel"
}
</blockquote></details>

Makes sense to use recursion only when needed. I've changed to while loop as suggested. However I kept $res rather than test $counter as I find it more readable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/27)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[agent-basic-js/generator.json, line 84 at r1](https://reviewable.io:443/reviews/stratumn/generators/27#-KyKVmywqhWiFGRvdZJy:-KyL1O4hQUpcQqHvrg5j:bmpis1k) ([raw file](https://github.com/stratumn/generators/blob/cb56d521fde55b8b46252f438d12508cee4c260f/agent-basic-js/generator.json#L84)):*
<details><summary><i>Previously, piedup wrote…</i></summary><blockquote>

I've changed the order to what it was. However I think it might be good to change the order in another commit because I don't think it makes sense to put fabric after dummy store.
</blockquote></details>

True, it is better to put fabricstore on the top but we have to keep in mind to fix generator tests when PR will be merged

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/27#-:-KyL2vh7RvnoFhCJNrCc:bnfp4nl)*

**Pull request merged**
