### PR TITLE
monitoring: mention in README

### PR DESCRIPTION
**Pull request by t-bast**
Detail monitoring setup and urls.
Fix mardownlint warnings.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/63)

### CODE REVIEW

**Comment by alexppxela** [comment]
Why cluster readme file is README instead of README.md?

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/63#-:-L9iik_Y-R24LlmMxv2x:b-ovuvmm)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/63#-:-L9iiy0nCTekpmBpUrqT:bnfp4nl)*

**Comment by t-bast** [comment]
Good point, updating that as well

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/63#-:-L9ipx97CRAU4PYVqhs2:b-tvbyp5)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/63#-:-L9iqIEn0NDfZJQEYN2J:bnfp4nl)*

**Pull request merged**
