### PR TITLE
Release sdk 0.2.0

### PR DESCRIPTION
**Pull request by alexppxela**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/32)

### CODE REVIEW

**Comment by bejito** [comment]
:champagne: 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32#-:-L0tvekxmQdacb8Rsxvr:bdqvwp9)*

**Comment by t-bast** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[agent-basic-js/generator.json, line 3 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0tw5-_5AMbO-8B_-XF:-L0tw5-_5AMbO-8B_-XG:b-5qng8v) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L3)):*
> ```JSON
> {
>   "name": "agent-basic-js",
>   "version": "0.1.0",
> ```

0.2.0? Or 0.2.0-rc1?

---

*[agent-basic-js/generator.json, line 9 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twEz8CP2Qe8f3_wZp:-L0twEz9mgCkHbn1jte3:bo7hn83) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L9)):*
> ```JSON
>   "variables": {
>     "generator": "agent-basic-js",
>     "agentdev": "indigoframework/agent-js:latest",
> ```

If this is the docker image name, it should still be a dev-alpine image (build is currently failing because I'm fighting docker, but it's the one that should be used when it will work :p). Same for agent-ui and tmpop-explorer. See 

---

*[agent-basic-js/files/docker-compose.dev.yml, line 16 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twy8-4YwWAyyZAqus:-L0twy80zyeD0UdSx1iV:bdnghrh) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/files/docker-compose.dev.yml#L16)):*
> ```YAML
>     - "4000:4000"
> {{- if $require_tmstore }}
>   indigoexplorer:
> ```

maybe rename tmpopexplorer?

---

*[agent-basic-js/files/docker-compose.dev.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0tx-wCiSgakx66zCTj:-L0tx-wCiSgakx66zCTk:b-816h64) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/files/docker-compose.dev.yml#L17)):*
> ```YAML
> {{- if $require_tmstore }}
>   indigoexplorer:
>     image: {{.indigoexplorer}}
> ```

Same?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[agent-basic-js/generator.json, line 11 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twDUul0pCW4dwVymC:-L0twDUul0pCW4dwVymD:bsgdv66) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L11)):*
> "agentdev": "indigoframework/agent-js:latest",
> "agentui": "indigoframework/agent-ui:latest",
>  "indigoexplorer": "indigoframework/tmpop-explorer:latest",

I think we should use versioned images for these as it's the case for SDK images. Do you have a good reason no to?

---

*[agent-basic-js/generator.json, line 79 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0txa3qbVBbUxYTb03y:-L0txa3qbVBbUxYTb03z:b2tbygn) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L79)):*
> ```JSON
>     "developmentStore": {
>       "type": "select:string",
>       "prompt": "Development store:",
> ```

How hard would it be to split this step in two? The user would only select a Tendermint Store and chose the backend afterwards?

---

*[agent-basic-js/generator.json, line 85 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twpWC7g-iOeRAbrBE:-L0twpWC7g-iOeRAbrBF:b-b5ofvi) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L85)):*
> ```JSON
>           "input": "1",
>           "value": "filetmpop",
>           "text": "Stratumn Tendermint Node With File Store"
> ```

I would replace Stratum by Indigo in those descriptions.
@conord33 do you have a recommendation regarding this? "Indigo Tendermint Node", "Indigo's Tendermint Node"... What would feel better?

---

*[agent-basic-js/generator.json, line 105 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twXL2al5924rpSas7:-L0twXL2al5924rpSas8:blqqr89) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L105)):*
> ```JSON
>           "input": "5",
>           "value": "fabricstore",
>           "text": "Stratumn Fabric Node"
> ```

Maybe "Hyperledger Fabric Node" would be better here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by conord33** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[agent-basic-js/generator.json, line 85 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twpWC7g-iOeRAbrBE:-L0xRMnFQB7evCQ3FrP8:bvxnw3h) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L85)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I would replace Stratum by Indigo in those descriptions.
@conord33 do you have a recommendation regarding this? "Indigo Tendermint Node", "Indigo's Tendermint Node"... What would feel better?
</blockquote></details>

I would say "Indigo's Tendermint Node" is a bit more natural sounding especially in the context of a propmt, but both could work. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[agent-basic-js/generator.json, line 3 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0tw5-_5AMbO-8B_-XF:-L0xVgxrAuUBDdFeT_Xv:bb74x83) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L3)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

0.2.0? Or 0.2.0-rc1?
</blockquote></details>

True

---

*[agent-basic-js/generator.json, line 9 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twEz8CP2Qe8f3_wZp:-L0xUadQchDl45VmYmZJ:b-o55wth) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L9)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

If this is the docker image name, it should still be a dev-alpine image (build is currently failing because I'm fighting docker, but it's the one that should be used when it will work :p). Same for agent-ui and tmpop-explorer. See 
</blockquote></details>

Yes, I was waiting for indigo-js container images delivery.

---

*[agent-basic-js/generator.json, line 11 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twDUul0pCW4dwVymC:-L0xUjpKoBq0nOro_7t7:b3ng3gg) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L11)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

> "agentdev": "indigoframework/agent-js:latest",
> "agentui": "indigoframework/agent-ui:latest",
>  "indigoexplorer": "indigoframework/tmpop-explorer:latest",

I think we should use versioned images for these as it's the case for SDK images. Do you have a good reason no to?
</blockquote></details>

I was waiting for indigo-js container images delivery.

---

*[agent-basic-js/generator.json, line 79 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0txa3qbVBbUxYTb03y:-L0xUuqFPLPv1-UuyctP:b-3wju29) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L79)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

How hard would it be to split this step in two? The user would only select a Tendermint Store and chose the backend afterwards?
</blockquote></details>

I'll test

---

*[agent-basic-js/generator.json, line 85 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twpWC7g-iOeRAbrBE:-L0xTrWTl1MKYQfjJpCt:bbl4i0f) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L85)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

I would say "Indigo's Tendermint Node" is a bit more natural sounding especially in the context of a propmt, but both could work. 
</blockquote></details>

_Indigo's_ done

---

*[agent-basic-js/generator.json, line 105 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twXL2al5924rpSas7:-L0xU0HmD7beF8tEItMz:b32w1t) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L105)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

Maybe "Hyperledger Fabric Node" would be better here
</blockquote></details>

Ok

---

*[agent-basic-js/files/docker-compose.dev.yml, line 16 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twy8-4YwWAyyZAqus:-L0xUOkXBYdPhYno3PM5:bb7f2mf) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/files/docker-compose.dev.yml#L16)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

maybe rename tmpopexplorer?
</blockquote></details>

done

---

*[agent-basic-js/files/docker-compose.dev.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0tx-wCiSgakx66zCTj:-L0xV5Mvq3WdWfO60kDf:bb7i16w) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/files/docker-compose.dev.yml#L17)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Same?
</blockquote></details>

idem

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[agent-basic-js/generator.json, line 9 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0twEz8CP2Qe8f3_wZp:-L0xWF1B9v4SZ76ELL2T:b-e5qu4k) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L9)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Yes, I was waiting for indigo-js container images delivery.
</blockquote></details>

They should all be ready with version 0.2.0-3 for Indigo-JS and 0.2.0-rc1 for the SDK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32#-:-L0yW-gQghPjMSXueisB:bnfp4nl)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[agent-basic-js/generator.json, line 79 at r1](https://reviewable.io:443/reviews/stratumn/generators/32#-L0txa3qbVBbUxYTb03y:-L0ygMVKOELwjsb_uIeS:b-1ytnnb) ([raw file](https://github.com/stratumn/generators/blob/fc4fa12fa4baff8d571da191b1bb3c335568f5f9/agent-basic-js/generator.json#L79)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I'll test
</blockquote></details>

It's ugly but it works

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by t-bast** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[agent-basic-js/files/agent/package.json, line 14 at r3](https://reviewable.io:443/reviews/stratumn/generators/32#-L0yog4_BsYRTz3EYXXV:-L0yog4_BsYRTz3EYXXW:b-57kief) ([raw file](https://github.com/stratumn/generators/blob/43b2f1e37631589f5009e4c46de4abf44a3fc4eb/agent-basic-js/files/agent/package.json#L14)):*
> ```JSON
>   "dependencies": {
>     "express": "^4.14.0",
>     "stratumn-agent": "^0.18.0"
> ```

You'll also need to update this to: "@indigoframework/agent": "^0.2.0"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by alexppxela** [comment]
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[agent-basic-js/files/agent/package.json, line 14 at r3](https://reviewable.io:443/reviews/stratumn/generators/32#-L0yog4_BsYRTz3EYXXV:-L0ypbnUielTyAQlvhLt:b2nid0f) ([raw file](https://github.com/stratumn/generators/blob/43b2f1e37631589f5009e4c46de4abf44a3fc4eb/agent-basic-js/files/agent/package.json#L14)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

You'll also need to update this to: "@indigoframework/agent": "^0.2.0"
</blockquote></details>

thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Comment by t-bast** [comment]
:lgtm:

---

Review status: 6 of 7 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32#-:-L0ypjI81uZRJ9omzfAX:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/32)*

**Pull request merged**
