### PR TITLE
generators: generate cluster

### PR DESCRIPTION
**Pull request by t-bast**
Provide an option to generate a test cluster.
It will pull a sample agent (via the agent-sample docker image) and spin up the number of Tendermint nodes provided and connect them via dial_seeds.
There are two small issues I need to fix (in later PRs):

- Agent-sample currently ignores fossilizers
- The dial script doesn't work because it looks like the RPC serialization changed in Tendermint 0.13.0, I need to update the message

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/38)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cluster/files/docker-compose.yml, line 17 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cMYGuh3jDAVY1ySxS:-L1cMYGuh3jDAVY1ySxT:bs74zok) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L17)):*
> ```YAML
> {{- end}}
>   agent:
>     image: {{.agentsample}}
> ```

Great idea to add an agentsample image.

---

*[cluster/files/docker-compose.yml, line 29 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cJyihgvJ-y4k7SxqG:-L1cJyihgvJ-y4k7SxqH:be84fzc) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L29)):*
> ```YAML
>     - {{$fossilizer}}
> {{- end}}
>   store:
> ```

When I sent you the compose file, I only put one tmstore, it should be great to add one instance of tmstore per tmapp?

---

*[cluster/files/docker-compose.yml, line 37 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cL2fsZ3ZyLSex9EAl:-L1cL2fsZ3ZyLSex9EAm:bt5op5) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L37)):*
> ```YAML
>     depends_on:
>     - tmapp1
> {{- if $require_postgresql }}
> ```

If one tmstore instance  per tmapp, we need one instance of db per tmstore. Or maybe a table per instance.

---

*[cluster/files/docker-compose.yml, line 63 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cLkXt6Q2cW39_1956:-L1cLkXt6Q2cW39_1957:b9qn4te) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L63)):*
> ```YAML
>     - ./config/common.env
>     - ./config/common.secret.env
>     command: [{{$tmstore}}, -home, "/data/tendermint", "-create_empty_blocks=false"]
> ```

You forgot the option "-unsafe" to enable dial to create network peer connections.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cluster/files/docker-compose.yml, line 29 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cJyihgvJ-y4k7SxqG:-L1pyICuA5FaDTP5DGt0:b-ul8jrf) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L29)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

When I sent you the compose file, I only put one tmstore, it should be great to add one instance of tmstore per tmapp?
</blockquote></details>

Good idea

---

*[cluster/files/docker-compose.yml, line 37 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cL2fsZ3ZyLSex9EAl:-L1pyLmCsLbyp5x_KwKA:bgeumwy) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L37)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

If one tmstore instance  per tmapp, we need one instance of db per tmstore. Or maybe a table per instance.
</blockquote></details>

Even with one instance per tmstore, how does it correctly find the postgres instance it should talk to? I need to dive a bit more into that

---

*[cluster/files/docker-compose.yml, line 63 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cLkXt6Q2cW39_1956:-L1pyXoBu3AcHWJaVrmD:bq38oxy) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L63)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

You forgot the option "-unsafe" to enable dial to create network peer connections.
</blockquote></details>

Ah that's probably why I was seeing it fail, thanks :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/files/docker-compose.yml, line 37 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cL2fsZ3ZyLSex9EAl:-L1q-a9zWTUjREXj9Jvh:b8dyjbf) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L37)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Even with one instance per tmstore, how does it correctly find the postgres instance it should talk to? I need to dive a bit more into that
</blockquote></details>

Use the `-url` flag on command line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/files/docker-compose.yml, line 37 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cL2fsZ3ZyLSex9EAl:-L1q0IHu_MPttby76Gzk:bswig4p) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L37)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Use the `-url` flag on command line
</blockquote></details>

Thanks, will do! I plan to integrate that change only after the 0.2.0 release though, it isn't stable/useful enough yet for outsiders

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/files/docker-compose.yml, line 37 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1cL2fsZ3ZyLSex9EAl:-L1q0Zx3IB9XOWw496Zm:b-vpbqpy) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/docker-compose.yml#L37)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Thanks, will do! I plan to integrate that change only after the 0.2.0 release though, it isn't stable/useful enough yet for outsiders
</blockquote></details>

good decision

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by such** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cluster/files/config/dev.secret.env, line 2 at r1](https://reviewable.io:443/reviews/stratumn/generators/38#-L1q7pnEJEQGTDXK-I26:-L1q7pnEJEQGTDXK-I27:b-c5kckk) ([raw file](https://github.com/stratumn/generators/blob/20c724a488f70b170c7a3081199373ec0c7589d2/cluster/files/config/dev.secret.env#L2)):*
> ```
> # A hard-to-guess salt used by the agent to validate callbacks.
> STRATUMN_SALT='{{secret 64}}'
> ```

This is not needed anymore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by such** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by alexppxela** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[cluster/files/docker-compose.yml, line 73 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1uzdl2zkP0GnH6H2vc:-L1uzdl2zkP0GnH6H2vd:b-d4qkiz) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/docker-compose.yml#L73)):*
> ```YAML
>     command: [{{$tmpopstore}}, -home, "/data/tendermint", "-create_empty_blocks=false", "-unsafe", "-url", "rethinkdb{{$node}}:28015"]
> {{- else }}
>     command: [{{$tmpopstore}}, -home, "/data/tendermint", "-create_empty_blocks=false", "-unsafe"]
> ```

If I start a filetmpop, I want to keep data for the next launch. It should be great to add another `if` with `-path` option to store data in file.

---

*[cluster/files/stratumn.json, line 13 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-j4ovDpB12R-1UC8:-L1v-j4ovDpB12R-1UC9:b-7nfmk4) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/stratumn.json#L13)):*
> ```JSON
>     "init": "strat run tm:init",
> {{- end}}
>     "tm:init": "sudo ./scripts/tminit.sh",
> ```

Is `sudo` necessary?

---

*[cluster/files/scripts/tminit.sh, line 15 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-_mQgwLJYb8hYN7j:-L1v-_mRavfjPT5r3Z-W:b-92jly8) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/scripts/tminit.sh#L15)):*
> ```Shell
> for i in `seq {{input `clusterSize`}}`; do
>     cp $(pwd)/genesis.json $(pwd)/tmapp$i/tendermint/genesis.json
> done
> ```

nit: shell script has to be ended by an empty line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cluster/files/docker-compose.yml, line 73 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1uzdl2zkP0GnH6H2vc:-L1v74Oxjxz1vjKLIrh6:b-cnd36i) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/docker-compose.yml#L73)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

If I start a filetmpop, I want to keep data for the next launch. It should be great to add another `if` with `-path` option to store data in file.
</blockquote></details>

That's already the case isn't it? In docker-compose.dev.yml in case you use filetmpop I mount the segments folder so it persists for next launch

---

*[cluster/files/stratumn.json, line 13 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-j4ovDpB12R-1UC8:-L1v7ECcQ88sQw3yeVK7:biuiv20) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/stratumn.json#L13)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Is `sudo` necessary?
</blockquote></details>

Unfortunately yes, because after the docker tendermint init run the tendermint files belong to root...I don't know how I can circumvent that

---

*[cluster/files/scripts/tminit.sh, line 15 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-_mQgwLJYb8hYN7j:-L1v7PImCswrCWZV1Dh_:b-y4ydsl) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/scripts/tminit.sh#L15)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: shell script has to be ended by an empty line
</blockquote></details>

Interesting, didn't know that. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by alexppxela** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[cluster/files/docker-compose.yml, line 73 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1uzdl2zkP0GnH6H2vc:-L1vHzJIZPhne_-Ef66M:be5zemb) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/docker-compose.yml#L73)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

That's already the case isn't it? In docker-compose.dev.yml in case you use filetmpop I mount the segments folder so it persists for next launch
</blockquote></details>

Ok forget, I didn't remember this... and didn't check

---

*[cluster/files/stratumn.json, line 13 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-j4ovDpB12R-1UC8:-L1vIOywhI4Ww9X2R1bF:b2rp2z9) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/stratumn.json#L13)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Unfortunately yes, because after the docker tendermint init run the tendermint files belong to root...I don't know how I can circumvent that
</blockquote></details>

It is the interest of post-init:linux. It calls `fix-tendermint-files-ownership.sh` to put the good rights on files.
This problem only occurs under linux.

---

*[cluster/files/scripts/tminit.sh, line 15 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-_mQgwLJYb8hYN7j:-L1vIgbyYSrr23-8JxwD:b-tyf0s0) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/scripts/tminit.sh#L15)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Interesting, didn't know that. Fixed.
</blockquote></details>

For compatibility with all shell interpreter versions.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/files/stratumn.json, line 13 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-j4ovDpB12R-1UC8:-L1vJSGNa27fS8KZaZ2N:bsd8g6f) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/stratumn.json#L13)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

It is the interest of post-init:linux. It calls `fix-tendermint-files-ownership.sh` to put the good rights on files.
This problem only occurs under linux.
</blockquote></details>

Ah cool, I'll play a bit with that then, thanks for the hint.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by t-bast** [comment]
Review status: 13 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[cluster/files/stratumn.json, line 13 at r2](https://reviewable.io:443/reviews/stratumn/generators/38#-L1v-j4ovDpB12R-1UC8:-L1vQq1n7orzx5dE699K:byv8tth) ([raw file](https://github.com/stratumn/generators/blob/12327a3c5997dfce1e702ef716381ac442eb3b5e/cluster/files/stratumn.json#L13)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Ah cool, I'll play a bit with that then, thanks for the hint.
</blockquote></details>

Thanks for this comment, it was the missing piece to get it all to work properly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 6 of 7 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[agent-basic-js/files/stratumn.json, line 17 at r4](https://reviewable.io:443/reviews/stratumn/generators/38#-L1vRs6NW-Qg5sYp1IzS:-L1vRs6NW-Qg5sYp1IzT:b-uzebqf) ([raw file](https://github.com/stratumn/generators/blob/4aa64b365f17b67f5530a6f471d98d6b15737115/agent-basic-js/files/stratumn.json#L17)):*
> ```JSON
> {{- else if eq $store "tmstore" }}
>     "init": "strat run tm:init",
>     "init:linux": "strat run tm:init && strat run tm:post-init:linux",
> ```

Well seen!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/38#-:-L1vSJnMI1iZ63Qmm6cP:bnfp4nl)*

**Pull request merged**
