### PR TITLE
agent-basic-js, cluster: bump tendermint image to 0.17.1

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/60)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[agent-basic-js/files/stratumn.json, line 23 at r1](https://beta.reviewable.io/reviews/stratumn/generators/60#-L9P81b5D0SrvHppio5Z:-L9P81b5D0SrvHppio5_:b85go45) ([raw file](https://github.com/stratumn/generators/blob/7ca61619120f2c681699bab8d940e2443a870a0c/agent-basic-js/files/stratumn.json#L23)):*
> ```JSON
>     "monitoring:post-init:linux": "./arch/linux/fix-monitoring-files-ownership.sh",
> {{- if eq $store "tmstore" }}
>     "tm:init": "docker run -it --rm -v \"$(pwd)/tendermint:/tendermint\" tendermint/tendermint:0.docker rm17.1 init",
> ```

ouch `docker rm`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/60)*

**Comment by t-bast** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/60)*

**Comment by simonvadee** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[agent-basic-js/files/stratumn.json, line 23 at r1](https://beta.reviewable.io/reviews/stratumn/generators/60#-L9P81b5D0SrvHppio5Z:-L9PGQruBL2rsIrl6VpP:b3itjsf) ([raw file](https://github.com/stratumn/generators/blob/7ca61619120f2c681699bab8d940e2443a870a0c/agent-basic-js/files/stratumn.json#L23)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

ouch `docker rm`
</blockquote></details>

damn that was my (one wee late) april fool's prank

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/60)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/60#-:-L9PHLHF8L5SLBcgJ_MF:bnfp4nl)*

**Pull request merged**
