### PR TITLE
monitoring: add monitoring containers to agent-basic-js

### PR DESCRIPTION
**Pull request by t-bast**
I haven't yet found a way to run Prometheus as its normal "nobody" user, it conflicts with the file permissions on the shared volume.
I'll try to fix that later.
Plugging all these pieces together exposed the fact there is apparently an issue with websockets between the agent and the store (probably because of the ochttp.Handler) that I'll investigate now.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/53)

### CODE REVIEW

**Comment by simonvadee** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[agent-basic-js/files/docker-compose.yml, line 151 at r1](https://beta.reviewable.io/reviews/stratumn/generators/53#-L8c6b0eBZOajwl1p91B:-L8c6b0eBZOajwl1p91C:b-pkjdkt) ([raw file](https://github.com/stratumn/generators/blob/a83148396ffab1ace469479715bf2e8b104862c9/agent-basic-js/files/docker-compose.yml#L151)):*
> ```YAML
>       - '--path.procfs=/host/proc' 
>       - '--path.sysfs=/host/sys'
>       - --collector.filesystem.ignored-mount-points
> ```

no quotes needed ?

---

*[agent-basic-js/files/docker-compose.yml, line 178 at r1](https://beta.reviewable.io/reviews/stratumn/generators/53#-L8c6mJM6sHlTZncMlXJ:-L8c6mJM6sHlTZncMlXK:bc9wbre) ([raw file](https://github.com/stratumn/generators/blob/a83148396ffab1ace469479715bf2e8b104862c9/agent-basic-js/files/docker-compose.yml#L178)):*
> ```YAML
>       - ./monitoring/grafana/provisioning/:/etc/grafana/provisioning/
>     ports:
>       - 7000:3000
> ```

doesn't port 3000 belong to the agent ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/53)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[agent-basic-js/files/docker-compose.yml, line 151 at r1](https://beta.reviewable.io/reviews/stratumn/generators/53#-L8c6b0eBZOajwl1p91B:-L8c77NhEupEazUvWdR5:b-rj22lx) ([raw file](https://github.com/stratumn/generators/blob/a83148396ffab1ace469479715bf2e8b104862c9/agent-basic-js/files/docker-compose.yml#L151)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

no quotes needed ?
</blockquote></details>

Nope. This was taken from their documentation.

---

*[agent-basic-js/files/docker-compose.yml, line 178 at r1](https://beta.reviewable.io/reviews/stratumn/generators/53#-L8c6mJM6sHlTZncMlXJ:-L8c7Aiv3vE8jMV1xnpy:bkyfr3d) ([raw file](https://github.com/stratumn/generators/blob/a83148396ffab1ace469479715bf2e8b104862c9/agent-basic-js/files/docker-compose.yml#L178)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

doesn't port 3000 belong to the agent ?
</blockquote></details>

We don't care, it's the internal port :)
Grafana exposes itself on port 3000, and I remap it to port 7000 because indeed our agent exposes 3000 already.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/53)*

**Comment by alexppxela** [comment]
It should be great to add a question to enable/disable monitoring stuff on generation
:lgtm:

---

Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/53#-:-L8c8JqoEscUmyk7z7n2:bx854s8)*

**Comment by t-bast** [comment]
Good idea, I'll add that

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/53#-:-L8c8q0y0Hcs6dNvezJR:bf036zj)*

**Pull request merged**
