### PR TITLE
0.1.0

### PR DESCRIPTION
**Pull request by alexppxela**
#15

### CODE REVIEW

**Comment by alexppxela** [comment]
Of course

**Comment by stephan83** [comment]
By the way merging to master won't be a problem after next release because the SDK will use the branch named after the version of the SDK.

**Comment by such** [comment]
`agent-basic-js/generator.json` should be updated with the compatible image version:
`tmstore` and `filetmpop` will have version `0.1.0`
`agent-ui` has version `0.4.0`
`indigo-explorer` has version `0.7.0

**Comment by simonvadee** [comment]
I merged branch 0.1.0-dev into at-multiple-processes to have a multi-process compliant validation file. I also updated the dependencies that @such mentioned in the previous comment but I left untouched the other ones, so filestore, dummystore/fossilizer... etc are still in 0.1.0-dev, should I also update them ?

**Pull request closed without merging**
