### PR TITLE
Add elasticsearchstore option

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/58)

### CODE REVIEW

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/58#-:-L9Fyhkb-L2BfoLv9shH:bnfp4nl)*

**Comment by such** [comment]
nice! :lgtm: 

---

Reviewed 9 of 9 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/58#-:-L9FystYBWw0SYt5iiwX:b25hj03)*

**Comment by t-bast** [comment]
Reviewed 8 of 9 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[agent-basic-js/files/README.md, line 80 at r1](https://beta.reviewable.io/reviews/stratumn/generators/58#-L9FzmxuE9_tIt0-Ggf_:-L9FzmxuE9_tIt0-Ggfa:b5nnoy0) ([raw file](https://github.com/stratumn/generators/blob/693c1ce0b073af22930fb3f62fec60ad91f6265d/agent-basic-js/files/README.md#L80)):*
> ```Markdown
> A Docker container is created for the database.
> {{- end}}
> {{- if eq $store "rethinktore"}}
> ```

nit: "rethinkstore" (missing 's')

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/58)*

**Comment by t-bast** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/generators/58)*

**Pull request merged**
