### PR TITLE
generators: fix and modernize

### PR DESCRIPTION
**Pull request by t-bast**
Fixed references to stratumn-agent package instead of @indigoframework/agent package.
Modernized JS.
Fixed empty lines in docker compose generated files.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/generators/36)

### CODE REVIEW

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/36#-:-L1RTwM8VqjCVzR4UBaW:bnfp4nl)*

**Comment by such** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[agent-basic-js/files/agent/index.js, line 46 at r1](https://reviewable.io:443/reviews/stratumn/generators/36#-L1RU5KmqONW1TLPBxPV:-L1RU5KmqONW1TLPBxPW:b-uwsw7q) ([raw file](https://github.com/stratumn/generators/blob/24f593106c263598a85fcea7e85453d73715f53c/agent-basic-js/files/agent/index.js#L46)):*
> ```JavaScript
> 
>   processFiles.forEach(file => {
>     const actions = require(`./lib/actions/${file}`).default;
> ```

you could probably import it as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/36)*

**Comment by such** [comment]
We should also update the tutorials and indigoframework.com with the new syntax.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/36#-:-L1RUH3x5MaHeBbirpv-:b-bljl4s)*

**Comment by t-bast** [comment]
Tutorials and indigoframework.com are already updated to the new syntax for the 0.2.0 release ;)

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[agent-basic-js/files/agent/index.js, line 46 at r1](https://reviewable.io:443/reviews/stratumn/generators/36#-L1RU5KmqONW1TLPBxPV:-L1RUd1JVxyIkLejmbti:b-evt4ns) ([raw file](https://github.com/stratumn/generators/blob/24f593106c263598a85fcea7e85453d73715f53c/agent-basic-js/files/agent/index.js#L46)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

you could probably import it as well
</blockquote></details>

I thought imports had to be at the top of the file, I'll test it out

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/36#-:-L1RUZL0nH7elY24Gchx:byvy1jn)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[agent-basic-js/files/agent/index.js, line 46 at r1](https://reviewable.io:443/reviews/stratumn/generators/36#-L1RU5KmqONW1TLPBxPV:-L1RVZ6WVDxv2_DHMDGR:b-5b9s0i) ([raw file](https://github.com/stratumn/generators/blob/24f593106c263598a85fcea7e85453d73715f53c/agent-basic-js/files/agent/index.js#L46)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I thought imports had to be at the top of the file, I'll test it out
</blockquote></details>

Imports and exports can only appear at the top of the file...so dynamic loading of modules can only be done via require :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/36)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/generators/36#-:-L1Rb7fXTGnlJOfoZb__:bnfp4nl)*

**Pull request merged**
